name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci

      # Install EAS CLI globally and expose it explicitly on PATH
      - run: |
          npm install --global eas-cli
          echo "$(npm prefix --global)/bin" >> $GITHUB_PATH
          eas --version

      # This enables task distribution via Nx Cloud
      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      # Prepend any command with "nx record --" to record its logs to Nx Cloud
      - run: npx nx record -- npx nx format:check --base="remotes/origin/main"
      - run: npx nx run-many -t lint test build typecheck e2e

      - run: npx nx fix-ci
        if: always()
